/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;

    
/**
 *
 * @author Roberto2022
 */
public class ClaseAbstractas extends javax.swing.JFrame {
    
   DefaultListModel hardware = new  DefaultListModel();
    /**
     * Creates new form ClaseAbstractas
     */
    public ClaseAbstractas() {
        initComponents();
        
        Lista.setModel(hardware);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textAñadir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        btnAñadir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textPosicion = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEliminarPorPosicion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Entradas de elementos");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(153, 255, 255), null, new java.awt.Color(0, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 27, 150, 22));

        textAñadir.setActionCommand(null);
        textAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(textAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 216, -1));

        jScrollPane1.setViewportView(Lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 209, -1));

        btnAñadir.setText("Añadir");
        btnAñadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        btnAñadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAñadirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAñadirKeyTyped(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Posición");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(255, 0, 0), null, java.awt.Color.white));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        textPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPosicionActionPerformed(evt);
            }
        });
        getContentPane().add(textPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        btnEliminarPorPosicion.setText("Eliminar por posicion");
        btnEliminarPorPosicion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarPorPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPorPosicionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPorPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
     String entrada = textAñadir.getText();
     hardware.addElement(entrada);
     textAñadir.setText(""); // Limpiar el campo de texto
     
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void textAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAñadirActionPerformed

    private void textPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPosicionActionPerformed

    private void btnEliminarPorPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPorPosicionActionPerformed
        int p = Integer.parseInt(textPosicion.getText()) - 1 ;
        hardware.remove(p);
    }//GEN-LAST:event_btnEliminarPorPosicionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        hardware.removeAllElements();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAñadirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAñadirKeyPressed
     String entrada = textAñadir.getText();
     hardware.addElement(entrada);
     textAñadir.setText("");
    }//GEN-LAST:event_btnAñadirKeyPressed

    private void btnAñadirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAñadirKeyTyped
     String entrada = textAñadir.getText();
     hardware.addElement(entrada);
     textAñadir.setText(""); // Limpiar el campo de texto
    }//GEN-LAST:event_btnAñadirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseAbstractas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseAbstractas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseAbstractas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseAbstractas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseAbstractas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPorPosicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textAñadir;
    private javax.swing.JTextField textPosicion;
    // End of variables declaration//GEN-END:variables
}
